services:
  web:
    build:
      context: .
    command: bash -c "bin/rails db:prepare && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/jingji_portfolio
      - bundle_cache:/usr/local/bundle
      - node_modules:/jingji_portfolio/node_modules
      - ./app/assets/builds:/jingji_portfolio/app/assets/builds
      - ./public/assets:/jingji_portfolio/public/assets
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/app_development
      REDIS_URL: redis://redis:6379/1
    env_file:
      - .env

  css:
    build:
      context: .
    command: bash -c "yarn install && yarn tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/tailwind.css --config ./tailwind.config.js --watch"
    volumes:
      - .:/jingji_portfolio
      - bundle_cache:/usr/local/bundle
      - node_modules:/jingji_portfolio/node_modules
      - ./app/assets/builds:/jingji_portfolio/app/assets/builds
      - ./public/assets:/jingji_portfolio/public/assets
    depends_on:
      - web

  js:
    build:
      context: .
    command: bash -c "yarn install && yarn esbuild app/javascript/*.* --bundle --sourcemap --format=esm --outdir=app/assets/builds --public-path=/assets --external:@hotwired/stimulus-loading --watch"
    volumes:
      - .:/jingji_portfolio
      - bundle_cache:/usr/local/bundle
      - node_modules:/jingji_portfolio/node_modules
      - ./app/assets/builds:/jingji_portfolio/app/assets/builds
      - ./public/assets:/jingji_portfolio/public/assets
    depends_on:
      - web

  db:
    image: postgres
    platform: linux/arm64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  node_modules:
  bundle_cache:
