sorcery:
  google_callback_url: "http;//localhost:3000/oauth/callback/google"

mailer:
  sender_email: <%= ENV['MAIL_FROM'] %>
  delivery_method: :letter_opener_web

default_url_options:
  host: 'localhost:3000'
