sorcery:
  google_callback_url: "https://gts-s.net/oauth/callback/google"

mailer:
  sender_email: <%= ENV['MAIL_FROM'] %>
  delivery_method: :smtp

default_url_options:
  protcol: 'https'
  host: 'gts-s.net'
