sorcery:
  google_callback_url: "http;//jingji-portfolio.onrender.com/oauth/callback/google"

mailer:
  sender_email: <%= ENV['MAIL_FROM'] %>
  delivery_method: :smtp

defauot_url_options:
  protcol: 'https'
  host: 'jingji-portfolio.onrender.com'
